{{- if not .Values.certManager.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-mtls
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "swim-ed254-consumer.labels" . | nindent 4 }}
    component: security
type: Opaque
data:
  keystore.p12: {{ .Values.mtls.clientKeystoreP12 | quote }}
  truststore.p12: {{ .Values.mtls.truststoreP12 | quote }}
stringData:
  keystore-password: {{ .Values.mtls.keystorePassword | quote }}
  truststore-password: {{ .Values.mtls.truststorePassword | quote }}
  amqp-username: {{ .Values.mtls.amqpUsername | quote }}
  amqp-password: {{ .Values.mtls.amqpPassword | quote }}
{{- end }}
