apiVersion: v1
kind: Secret
metadata:
  name: swim-ed254-consumer-mtls
  namespace: swim-demo
  labels:
    app: swim-ed254-consumer
    component: security
    app.kubernetes.io/part-of: swim-ed254
type: Opaque
data:
  client-keystore.p12: ""
  truststore.p12: ""
  keystore-password: Y2hhbmdlbWU=
  truststore-password: Y2hhbmdlbWU=
